#!/bin/bash

function effects {
	compton --shadow-exclude 'g:e:Conky' --config ~/.config/compton.conf &
}

function screensaver {
	xset -dpms & xset s noblank & xset s off &
	xautolock -time 20 -locker slock &
}

function menu {
	tint2 &
	volwheel &
	nm-applet &
	}

function wallpaper {
	nitrogen --restore &
	#if [ -r ~/.wallpaper.png ]; then
	#   hsetroot -fill ~/.wallpaper.png &
	#else
	#   hsetroot -fill /usr/share/wallpapers/archbang-sky.png &
	#fi
	#xwinwrap -g 1920x1080 -ni -s -nf -b -un -argb -sh rectangle -fdt -- mpv -wid WID --keepaspect=no --loop /users/grace/.wm/schemes/sakura/wallpaper.webm &
	#xwinwrap -g 1920x1080 -ni -s -nf -b -un -argb -sh rectangle -fdt -- gifview -w WID -a /users/grace/.wm/schemes/sakura/wallpaper.gif &
}

#function setDisplay {
#	xrandr --output VGA1 --mode 1680x1050 --rate 60.0 --output LVDS1 --off &
#}

function setDisplay {
	xrandr --output VGA-1 --mode 1920x1080 --rate 60.0 &
}
